#!/bin/bash

echo "Content-Type: text/html"
echo ""
echo "<html>"
echo "<head><title>Shell CGI Test</title></head>"
echo "<body>"
echo "<h1>Shell CGI Script Working!</h1>"
echo "<h2>Environment Variables:</h2>"
echo "<ul>"
echo "<li>REQUEST_METHOD: $REQUEST_METHOD</li>"
echo "<li>QUERY_STRING: $QUERY_STRING</li>"
echo "<li>SCRIPT_NAME: $SCRIPT_NAME</li>"
echo "<li>SERVER_NAME: $SERVER_NAME</li>"
echo "<li>SERVER_PORT: $SERVER_PORT</li>"
echo "</ul>"
echo "<h2>Current Date:</h2>"
echo "<p>$(date)</p>"
echo "</body>"
echo "</html>"